### ISSUE TITLE
Error when importing EMP sequence data without setting the optional file name parameter

### ISSUE THREAD

**Issue by bernt-matthias** [qiime2/galaxy-tools#60]
When importing (EMPSingle..) I got the following error when I do not specify an input name (input name is documented as optional):

```
Unexpected error importing data:
[Errno 21] Is a directory: '/work/son
galax/galaxy/database/jobs_directory/
000/249/249581/working/q2galaxy-
import4f2_jqeh/'
:(
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-6vi7ogh0 because the default path (/home/qiime2/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
File "/opt/conda/envs/qiime2-2023.5/bin/q2galaxy", line 11, in <module>
sys.exit(root())
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/click/core.py", line 760, in invoke
return _callback(*args, **kwargs)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/q2galaxy/main.py", line 96, in run
builtin_runner(action, config)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/q2galaxy/core/drivers/builtins.py", line 24, in builtin_runner
tool(inputs, stdio=stdio)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/q2galaxy/core/drivers/builtins.py", line 43, in import_data
artifact = import_name_data(type, format, files_to_move,
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/q2galaxy/core/drivers/stdio.py", line 38, in wrapped
return function(*args, **kwargs)
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/q2galaxy/core/drivers/builtins.py", line 84, in import_name_data
qiime2.util.duplicate(src, os.path.join(dir, dst))
File "/opt/conda/envs/qiime2-2023.5/lib/python3.8/site-packages/qiime2/util.py", line 82, in duplicate
raise OSError(errno.EISDIR, "Is a directory", dst)
IsADirectoryError: [Errno 21] Is a directory: '/work/songalax/galaxy/database/jobs_directory/000/249/249581/working/q2galaxy-import4f2_jqeh/'```

Probably related https://github.com/qiime2/galaxy-tools/issues/50

Workaround: set dataset name

**Comment by ebolyen** [comment]
I think you're right, there seems to be a bit of a mismatch with what `name` does or doesn't mean to the driver. Let's merge this into #50, as I think we may need to rethink some things on our end.
